name: Debug Secrets

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print secret for debugging
        env:
          DEBUG_MESSAGE: ${{ secrets.DEBUG_MESSAGE }}
        run: |
          echo "DEBUG: The secret message is: $DEBUG_MESSAGE"
