name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          cd ~/obi-share

          git pull origin main

          source venv/bin/activate

          pip install -r requirements.txt

          pm2 restart fastapi-backend || pm2 start uvicorn --name "fastapi-backend" --interpreter python3 -- "main:app" --reload --host 0.0.0.0 --port 8000
        EOF
